name: 同步到 Gitee

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  sync-to-gitee:
    runs-on: ubuntu-latest
    steps:
      - name: 迁出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 镜像推送到 Gitee
        uses: wearerequired/git-mirror-action@master
        with:
          source-repo: "https://github.com/${{ github.repository }}.git"
          destination-repo: "https://${{ secrets.GITEE_USERNAME }}:${{ secrets.GITEE_TOKEN }}@gitee.com/${{ secrets.GITEE_USERNAME }}/${{ github.event.repository.name }}.git"