name: 同步到 Gitee

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  sync-to-gitee:
    runs-on: ubuntu-latest
    steps:
      - name: 迁出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 镜像推送到 Gitee（自动创建仓库）
        uses: Yikun/hub-mirror-action@v1.5
        with:
          src: github/zeguoxiao
          dst: gitee/xiao-zeuguo
          dst_key: ${{ secrets.GITEE_TOKEN }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          account_type: user
          clone_style: https
          force_update: true
          static_list: ${{ github.event.repository.name }}
